version: "3.9"
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tablita
      - URL=http://3.86.248.186
    networks:
      - express-network

  express-api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_HOST=database
      - DB_NAME=tablita
    depends_on:
      - database
    networks:
      - express-network
networks:
  express-network: